#!/usr/bin/env bash

# https://ensembl-hive.readthedocs.io/en/version-2.5/quickstart/install.html#ehive-installation-setup
# https://ensembl-hive.readthedocs.io/en/version-2.5/contrib/alternative_meadows.html#other-job-schedulers
# https://github.com/tweep/ensembl-hive-slurm

APP_DIR='/apps'
LOG='/tmp/ehive.log'

# Prerequisites
yum install -y graphviz gnuplot cpan | tee -a ${LOG}
. "${HOME}/.bashrc" | tee -a ${LOG}
cpan App::cpanminus << EOF
yes
local::lib
yes
yes
EOF

# Slurm Meadow
cd "${APP_DIR}" && git clone https://github.com/tweep/ensembl-hive-slurm.git | tee -a ${LOG}

# Main repository
cd "${APP_DIR}" && git clone https://github.com/Ensembl/ensembl-hive.git | tee -a ${LOG}
cd "${APP_DIR}/ensembl-hive" && cpanm --installdeps --with-recommends . | tee -a ${LOG}

perl -v | tee -a ${LOG}
mysql -V | tee -a ${LOG}
dot -V | tee -a ${LOG}
gnuplot -V | tee -a ${LOG}
cpanm -V | tee -a ${LOG}
